os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev
      - g++-8

sudo: enabled
language: cpp
compiler: g++

before_install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt update

    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get install gcc-8 g++-8

    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

    export CC=gcc-8
    export CXX=g++-8
  fi

script:
    - sudo chmod +x build.sh
    - ./build.sh
    - ./FakeStringUnitTests
    
    