os:
  - linux
  - osx
  - windows

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

sudo: enabled
language: cpp
compiler: g++

before_install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt update

    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get install gcc-8 g++-8

    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

    export CC=gcc-8
    export CXX=g++-8
  fi

matrix:
    include:
        -name: "Build"
        env:
        - CC="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-gcc"
        - CXX="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-g++"
        script:
        - ./build.sh
  
        -name: "Unit Tests"
        script: 
        - ./FakeStringUnitTests
  
  